### ISSUE TITLE
dsst program lacks of <fftw3.h>

### ISSUE THREAD

**Issue by Eric-Zhang1990** [ferzik85/dsst#3]
Hello, author, your dsst program lacks of <fftw3.h>, could you please upload fftw3.h>? 
Thank you very much!

**Comment by ferzik85** [comment]
install fftw library from here http://www.fftw.org/

**Comment by Eric-Zhang1990** [comment]
Dear ferzik85:
       I install the fftw, but I find that a lot variates are not defined, like "scale_window", "currentScaleFactor", etc.
       Could you please send me a intact dsst program?
       Thank you!

**Comment by ferzik85** [comment]
Eric-Zhang1990, Sorry, but you should figure out yourself how to compile the program on your machine, on my machine everything is working, "scale_window", "currentScaleFactor", etc are defined in
https://github.com/ferzik85/dsst/blob/master/dsst/DSSTTracker.h
Also don't forget to set up open cv

**Comment by ferzik85** [comment]
Eric-Zhang1990, also to understand program better, plz see
// [1] Martin Danelljan, Gustav Huger, Fahad Shahbaz Khan and Michael Felsberg.
//     "Accurate Scale Estimation for Robust Visual Tracking".
//     Proceedings of the British Machine Vision Conference(BMVC), 2014,
//     Winner of VOT 2014 challenge.
